version: "3"
services:
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json:cached
      - ./node_modules:/app/node_modules:cached
      - ./scripts:/app/scripts:cached
      - ./src:/app/src:cached
      - ./nodemon.json:/app/nodemon.json:cached
      - ./tsconfig.json:/app/tsconfig.json:cached
      - ./.eslintrc.json:/app/.eslintrc.json:cached
      - ./.prettierrc.js:/app/.prettierrc.js:cached
    networks:
      - app
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"

  db:
    container_name: db
    networks:
      - app
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  pgweb:
    container_name: pgweb
    networks:
      - app
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://username:password@db:5432/database?sslmode=disable
    depends_on:
      - db

networks:
  app:
