apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: app
spec:
  rules:
  - host: app.com
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 4000
  tls:
  - hosts:
    - app.com
    secretName: app-cert
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    com.example: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    com.example: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.example: app
    spec:
      restartPolicy: Always
      containers:
      - image: some-regeistry.com/example/app:$TAG
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        name: app
        ports:
        - containerPort: 4000
        env:
          - name: NODE_ENV
            value: production
          - name: POSTGRES_USER
            value: good_username
          - name: POSTGRES_PASSWORD
            value: good_password
          - name: POSTGRES_PORT
            value: 5432
          - name: POSTGRES_HOST
            value: good_host
          - name: POSTGRES_DB
            value: good_db
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
